add new file - First homework
vadimmovlamov/reactJS pull request #1
Opened 2022-07-17 13:13 UTC by vadimmovlamov

my first App in react

2022-07-18 10:16 UTC, Boobaley requested changes

2022-07-18 10:16 UTC, Boobaley commented on .vscode/launch.json
> +}
this folder must not be in repo

2022-07-18 10:16 UTC, Boobaley commented on app/src/pages/Counter/Containers/CounterContainer.js
> +    constructor(props) { // для чего мы создаем конструктор
мы можем его и не создавать. Я говорил про это

2022-07-18 10:16 UTC, Boobaley commented on app/src/pages/Counter/Containers/CounterContainer.js
> +        )
issue: You call setState every time. Rework you logic in the following way: I want to call setState only if ... your statement...

2022-07-18 10:16 UTC, Boobaley commented on app/src/pages/Counter/Containers/CounterContainer.js
> +        />
use prettier

2022-07-18 10:16 UTC, Boobaley commented on app/src/pages/Counter/components/Counter/index.js
> +      {countValue % 2 !== 0 ? <div className={styles.screenDouble}>Введено нечетное число</div> : countValue === 0 ? null : <div className={styles.screenDouble}>Введено четное число</div>}
so hard.

`{countValue > 0 && <div className={styles.screenDouble}>{countValue % 2 === 0 ? 'Введено четное число' :   'Введено нечетное число'}</div> }`

2022-07-27 23:34 UTC, merged

2022-07-27 23:34 UTC, vadimmovlamov commented
1